services:
  mysql:
    image: mysql:8.3.0
    user: ${UID}:${GID}
    ports:
    - ${MYSQL_HOST_PORT}:3306
    volumes:
    - ./db/mysql/data:/var/lib/mysql
    - ./db/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    env_file:
    - .env
    - .mysql.env
