volumes:
  mysql-volume:
services:
  mysql:
    image: mysql:8.3.0
    user: ${USER_ID}:${GROUP_ID}
    ports:
    - ${MYSQL_HOST_PORT}:3306
    volumes:
    - mysql-volume:/var/lib/mysql
    - ./db/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
